### ISSUE TITLE
Support for Front Matter with Markdown page metadata

### ISSUE THREAD

**Issue by gwpl** [executablebooks/mdformat#396] opened 2023-04-27 13:48 UTC
### Context

Many markdown files I have in repositories contain YAML Front Matter (

* https://jekyllrb.com/docs/front-matter/
* https://gohugo.io/content-management/front-matter/
...
)

Currently mdformat just formats all of this into one line.

### Proposal

Can mdformat identify (or have flag) to identify and ignore YAML front matter. 

(As ambitious goal, pass it through some YAML formatter if available, but just leaving it as it is would be already huge improvement)

**Comment by hukkin** [comment] 2023-04-27 17:42
Closing as dupe of https://github.com/executablebooks/mdformat/issues/372.

See https://github.com/butler54/mdformat-frontmatter for frontmatter support today.

This may happen in https://github.com/executablebooks/mdformat/issues/332

**Closed by hukkin** 2023-04-27 17:42 UTC
Labels: enhancement
