### ISSUE TITLE
Doesn't handle escaped pipe symbols inside tables

### ISSUE THREAD

**Issue by sanmai-NL** [executablebooks/mdformat#471] opened 2024-11-04 11:24 UTC
### Describe the bug

**context**
When I do ___.

```markdown
| Label                      | Person |
| -------------------------- | ------ |
| ‘Component 📦 \| Frontend’  | Joe   |
```

**expectation**
I expected ___ to occur.

```markdown
| Label                      | Person |
| -------------------------- | ------ |
| ‘Component 📦 \| Frontend’  | Joe   |
```

**bug**
But instead ___ happens

```markdown
| Label                      | Person |
| -------------------------- | ------ |
| ‘Component 📦 | Frontend’  | Joe    |
```

mdformat 0.7.17

### Reproduce the bug

```markdown
| Label                      | Person |
| -------------------------- | ------ |
| ‘Component 📦 \| Frontend’  | Joe   |
```

```console
$ mdformat file.md
```

### List your environment

mdformat 0.7.17

**Comment by hukkin** [comment] 2024-11-04 11:31
Hey do you have `mdformat-tables` installed? I can't reproduce.

```console
(venv) hukkin@foo:~$ cat f.md 
| Label                      | Person |
| -------------------------- | ------ |
| ‘Component 📦 \| Frontend’  | Joe   |
(venv) hukkin@foo:~$ mdformat --version
mdformat 0.7.18 (mdformat_tables: 1.0.0)
(venv) hukkin@foo:~$ mdformat f.md 
(venv) hukkin@foo:~$ cat f.md 
| Label                      | Person |
| -------------------------- | ------ |
| ‘Component 📦 \| Frontend’ | Joe    |
```

**Comment by sanmai-NL** [comment] 2024-11-04 11:34
I think so, how can I find out? I'm not running this out of a venv right now.

**Comment by hukkin** [comment] 2024-11-04 11:34
Run 
```console
mdformat --version
```

**Comment by sanmai-NL** [comment] 2024-11-04 12:03
That gives the output I gave. I found out I had a Python 3.11 installation via Homebrew, which contained this package (likely installed via pip), and removed it. I reinstalled `mdformat` via Homebrew, which gives me 0.7.18 and hopefully, a guarantee that mdformat-tables isn't installed. But the result is the same.

**Comment by hukkin** [comment] 2024-11-04 12:07
>  I reinstalled mdformat via Homebrew, which gives me 0.7.18 and hopefully, a guarantee that mdformat-tables isn't installed.

To clarify, you _need_ that plugin. Any plugins you have installed will be listed if you run `mdformat --version`. If you see no plugins, you have no plugins installed.

**Comment by sanmai-NL** [comment] 2024-11-04 12:38
Thanks for telling me.
I wouldn't expect `mdformat` to break Markdown due to the absence of a plugin.
But I see now that tables aren't CommonMark. 
Table content is still syntactical yet meaningless in CommonMark.
Which is why you cannot throw a fault in this case.
It's a pity `mdformat-tables` isn't available on Homebrew. 
This means I will always have to have a venv handy. 
Normally, I install `mdformat` and various plugins inside a venv as dev dependencies, but not when I use `mdformat` for non-Python projects. 
Installing it globally using just pip is not advised.

**Comment by sanmai-NL** [comment] 2024-11-04 13:18
It's possible in various ways but at that point, I prefer to create this venv ...

As for this issue, are you open to improving the docs to warn about breaking Markdown with tables without the plugin? I see some content that's related to that topic in the README, but `mdformat-tables` isn't mentioned, is it?

Dependent on this the issue can be closed.

**Comment by hukkin** [comment] 2024-11-04 13:24
The README mentions mdformat-gfm, and has [this](https://github.com/executablebooks/mdformat?tab=readme-ov-file#why-does-mdformat-backslash-escape-special-syntax-specific-to-mkdocs--hugo--obsidian--github--some-other-markdown-engine) FAQ entry. I don't want to mention every possible syntax extension by name. If you see a way to improve besides that, feel free to create an issue or PR to suggest!

Closing this issue.

**Closed by hukkin** 2024-11-04 13:24 UTC
Labels: invalid
