### ISSUE TITLE
Allow wrapping option of 1 sentence per line

### ISSUE THREAD

**Issue by unparalleled-js** [executablebooks/mdformat#374] opened 2022-12-15 15:18 UTC
### Context

Our general rule is 1 sentence per line in Markdown, regardless of long or short that sentence is.
It would be nice if we could have that as an option for `--wrap`.

### Proposal

`--wrap sentence` where `sentence` is the new enum value

**Comment by hukkin** [comment] 2022-12-15 15:20
Closing as dupe of https://github.com/executablebooks/mdformat/issues/4

**Closed by hukkin** 2022-12-15 15:20 UTC
Labels: enhancement
