### ISSUE TITLE
On/off comments

### ISSUE THREAD

**Issue by pawamoy** [executablebooks/mdformat#436] opened 2024-04-14 18:21 UTC
### Context

I'm evaluating mdformat in one of my projects (actually my MkDocs-based website).

It's super useful already, but obviously there are some incompatibilities between the parser used by mdformat and the one used by MkDocs (Python-Markdown). I don't mind these incompatibilities, and would actually like to write plugins myself to support Python-Markdown extensions :slightly_smiling_face: (if it's at all possible :thinking:?)

In the meantime, it would be great if I could add on/off comments to my Markdown document to prevent mdformat from formatting some snippets. Typically, mkdocstrings instructions that look like this:

```md
::: path.to.object
    options:
      show_source: false
```

...and get reformatted like this:

```md
::: path.to.object options: show_source: false
```

### Proposal

I would suggest supporting on/off comments like the following:

```md
<!-- mdformat: off -->

::: path.to.object
    options:
      show_source: false

<!-- mdformat: on -->
```

I have implemented [the same thing for blacken-docs](https://github.com/adamchainz/blacken-docs/pull/287) (though still waiting review), so could probably send a PR to mdformat too, if this feature is something you'd like to have :slightly_smiling_face:

**Comment by hukkin** [comment] 2024-08-09 21:35
Hi!
This seems like a dupe of https://github.com/executablebooks/mdformat/issues/53 so closing. This feature is very welcome, but behavior should be well defined. I had some concerns: https://github.com/executablebooks/mdformat/issues/53#issuecomment-705034415

Might be good to spec out the corner cases prior to actual implementation.

**Closed by hukkin** 2024-08-09 21:35 UTC
Labels: enhancement

**Comment by pawamoy** [comment] 2024-08-10 11:34
Ah, sorry for missing #53! Will continue discussion there, thanks :slightly_smiling_face:
