### ISSUE TITLE
Escape square brackets less

### ISSUE THREAD

**Issue by hukkin** [executablebooks/mdformat#112] opened 2021-01-14 12:56 UTC
Linked issue https://github.com/executablebooks/mdformat/issues/110

Prettier seems to do a better job at square bracket escaping. Mdformat currently always escapes square brackets (to not accidentally produce link label enclosures) whereas it seems that Prettier keeps escapes from the source text.

The token stream we get from the parser is mainly just abstract syntax, so we don't know if the escapes were there in the source or not. Thus doing exactly what Prettier does is not currently easy to implement.

Like with other escapes, we could try to come up with logic that detects cases where link label enclosure certainly will not be accidentally produced and not escape if that is the case.

Note that this approach when implemented well enough can actually be an improvement over simply sustaining escapes from source, as it will automatically remove needless escapes.

**Comment by hukkinj1** [comment] 2021-04-07 12:03
I'm starting to think it might be better to leave this as `won't fix` due to the instability caused by unescaped square brackets.

- Square brackets connect with others even if they are not on the same line.
- Given markdown like
  ```markdown
  [blaa]
  ```
  this is not a link. But if someone adds a link reference definition with the label `blaa` then suddenly it is a link.
- Given markdown like
  ```markdown
  blii [blaa]: blipblop
  ```
  if someone removes the initial `blii` then suddenly we have a link reference definition and all text disappears when rendered

**Comment by hukkinj1** [comment] 2021-04-07 12:40
If this is not left as a `won't fix`, then the following heuristic could be useful:

Escape all square brackets unless all of the following are true for a closed pair of brackets (`[` + `text` + `]`):
- the brackets enclose a text containing no square brackets,
- the text is not a `used_ref` (a link label used in a valid link or image)
- the enclosure is followed by a character other than `:` or `(`

**Comment by butler54** [comment] 2021-08-24 05:39
I'll put a plus one on fixing this.

**Comment by jamesquilty** [comment] 2021-11-26 23:33
FWIW, the ability to disable escaping altogether is next on my list of configurations to implement in my fork.

**Comment by hukkin** [comment] 2022-03-01 14:18
Thanks @mdeweerd! That's not related to square bracket escapes so I moved it to a separate issue.

**Comment by mlschechter** [comment] 2022-06-07 17:03
I think this issue also impacts using `mdformat` with Hugo [cross-references](https://gohugo.io/content-management/cross-references/#readout).

The original content:
```markdown
[company branding]({{< ref "company-branding.md" >}} "Branding Configuration")
```

And the formatted result
```markdown
\[company branding\]({{\< ref "company-branding.md" >}} "Branding Configuration")
```

This will break the Hugo rendering; could you please let me know if there is a configuration parameter or plugin that will prevent this happening?

**Comment by sanzoghenzo** [comment] 2023-06-23 09:47
This is also an issue with [`mkdocstrings` cross-references](https://mkdocstrings.github.io/usage/#cross-references) when used in manually created markdowns (in my case the root README.md).

```md
[`Object 1`][package.module.object1]
```

even an option to disable the escaping would be a huge improvement for my use case (we don't usually use reference links, so the likelihood to break things is really low)

**Comment by afuetterer** [comment] 2024-03-22 08:06
> This is also an issue with [`mkdocstrings` cross-references](https://mkdocstrings.github.io/usage/#cross-references) when used in manually created markdowns (in my case the root README.md).
> 
> ```
> [`Object 1`][package.module.object1]
> ```
> 
> even an option to disable the escaping would be a huge improvement for my use case (we don't usually use reference links, so the likelihood to break things is really low)

Anybody running into this, have a look at [mdformat-mkdocs](https://github.com/KyleKing/mdformat-mkdocs) with the `--ignore-missing-references` flag. It solved the issue for me when using [mkdocstrings](https://mkdocstrings.github.io/usage/#cross-references).

**Comment by mdeweerd** [comment] 2024-03-22 08:49
@afuetterer  Thenk you for sharing - it reminds of the alternative: have an option to control the behavior.  And it got me back to this page.

Personally I think that even a standalone `[text]` should be left untouched by default and just generate a warning message suggesting to escape the brackets or add the (equivalent of the) --ignore-missing-references argument or --escape-missing-references to have them automatically escaped.

Personally I am not into mdformat to have "everything" "fixed" (in some cases breaking it).  There are also quite a few developers that do not want tools to make many "intrusive" changes.

My original issue occurred when I had two spacea after the markdown tickbox `-  [ ]` and the tickbox was escaped.

**Comment by zubieta** [comment] 2024-08-02 03:00
Hi everyone! I'm pretty interested in fixing this. I don't know the mdformat codebase, but I'll be willing to take a stab at implementing this (even if slowly), if someone is willing to point me in the right direction and hold my hand a little.

> If this is not left as a `won't fix`, then the following heuristic could be useful:
> 
> Escape all square brackets unless all of the following are true for a closed pair of brackets (`[` + `text` + `]`):
> 
>     * the brackets enclose a text containing no square brackets,
> 
>     * the text is not a `used_ref` (a link label used in a valid link or image)
> 
>     * the enclosure is not followed by `:` or `(`

**Comment by ncimino** [comment] 2024-08-15 12:19
`mdformat` should support:

```
Remaining TODOs:

- [ ] Add cookies dialog

```

It instead escapes it as: `- \[ \] ...`

There is no way to fix this using current options. I would consider this a bug.

**Comment by ncimino** [comment] 2024-08-15 12:55
> `mdformat` should support:
> 
> ```
> Remaining TODOs:
> 
> - [ ] Add cookies dialog
> ```
> 
> It instead escapes it as: `- \[ \] ...`
> 
> There is no way to fix this using current options. I would consider this a bug.

Found a fix that works for me:
- https://github.com/hukkin/mdformat-gfm/issues/23

```
  - repo: local
    hooks:
      - id: mdformat
        name: mdformat
        entry: mdformat
        language: python
        additional_dependencies:
          - mdformat-toc
          - mdformat-gfm       # <--- This is the fix for me
        args: ["--wrap", "120", "--number", "--end-of-line", "lf"]
        types: [markdown]
        files: .
```

**Closed** 2024-10-26 16:33 UTC
Labels: enhancement
