### ISSUE TITLE
mdformat-config fails when encountering escaped double quotes in json codeblocks.

### ISSUE THREAD

**Issue by butler54** [executablebooks/mdformat#289] opened 2021-12-08 21:49 UTC
### Describe the problem

If you have a markdown file that is otherwise okay and you add a codeblock of json with escaped double quotes like this within the markdown document (review source .. not rendered output in GH)

```json
{
  "double_quotes": "Escaped\"Double quotes\"."
}
```

You get a random error something like this:
```shell
pre-commit run mdformat --all-files
mdformat.................................................................Failed
- hook id: mdformat
- files were modified by this hook

Warning: Failed formatting content of a json code block (line 429 before formatting)
Warning: Failed formatting content of a json code block (line 518 before formatting)
Warning: Failed formatting content of a json code block (line 60 before formatting)
Warning: Failed formatting content of a json code block (line 118 before formatting)
Warning: Failed formatting content of a json code block (line 213 before formatting)
Warning: Failed formatting content of a json code block (line 7 before formatting)
Warning: Failed formatting content of a json code block (line 60 before formatting)
Warning: Failed formatting content of a json code block (line 118 before formatting)
Warning: Failed formatting content of a json code block (line 213 before formatting)
Warning: Failed formatting content of a json code block (line 435 before formatting)
Warning: Failed formatting content of a json code block (line 717 before formatting)
Warning: Failed formatting content of a json code block (line 857 before formatting)
Warning: Failed formatting content of a json code block (line 93 before formatting)
Warning: Failed formatting content of a json code block (line 210 before formatting)
Warning: Failed formatting content of a json code block (line 254 before formatting)
Warning: Failed formatting content of a json code block (line 301 before formatting)
```
Removing the escaped double quotes eliminates the problem

### Steps to reproduce

Add the offending json code block to a file indexed with mdformat.
Run
Observe the errors

### The version of Python you're using

ython 3.9.9 (main, Nov 21 2021, 03:23:44)  [Clang 13.0.0 (clang-1300.0.29.3)] on darwin

### Your operating system

Mac os

### Versions of your packages

Running in pre-commit with the following pre-commit config:
```yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.11
    hooks:
    - id: mdformat
      exclude: "CHANGELOG.md|docs/mkdocs_code_of_conduct.md|docs/api_reference|tests/data/author|docs/contributing/mkdocs_contributing.md"
      additional_dependencies:
      - mdformat-tables
      - mdformat-config
      - mdformat-frontmatter
      - mdformat-gfm
```
pre-commit autoupdate runs on every build.

**Comment by hukkin** [comment] 2021-12-08 22:15
Thanks for the issue!

Unfortunately I'm not able to reproduce:
~~~~console
foo@bar:~$ python3 -m venv testvenv
foo@bar:~$ source testvenv/bin/activate
(testvenv) foo@bar:~$ printf '```markdown\n{\n  \"double_quotes\": \"Escaped\\\"Double quotes\\\".\"\n}\n```\n' > test.md
(testvenv) foo@bar:~$ cat test.md 
```markdown
{
  "double_quotes": "Escaped\"Double quotes\"."
}
```
(testvenv) foo@bar:~$ pip install mdformat-gfm mdformat-frontmatter mdformat-config
Collecting mdformat-gfm
  Downloading mdformat_gfm-0.3.5-py3-none-any.whl (4.9 kB)
Collecting mdformat-frontmatter
  Using cached mdformat_frontmatter-0.4.1-py3-none-any.whl (4.5 kB)
Collecting mdformat-config
  Downloading mdformat_config-0.1.3-py3-none-any.whl (3.1 kB)
Collecting mdit-py-plugins<0.4.0,>=0.2.0
  Downloading mdit_py_plugins-0.3.0-py3-none-any.whl (43 kB)
     |████████████████████████████████| 43 kB 523 kB/s 
Collecting mdformat<0.8.0,>=0.7.5
  Downloading mdformat-0.7.11-py3-none-any.whl (27 kB)
Collecting markdown-it-py[linkify]
  Using cached markdown_it_py-2.0.0-py3-none-any.whl (83 kB)
Collecting mdformat-tables>=0.4.0
  Using cached mdformat_tables-0.4.1-py3-none-any.whl (4.6 kB)
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.17.17-py3-none-any.whl (109 kB)
     |████████████████████████████████| 109 kB 13.6 MB/s 
Collecting toml>=0.10.0
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tomli>=1.1.0
  Using cached tomli-1.2.2-py3-none-any.whl (12 kB)
Collecting importlib-metadata>=3.6.0; python_version < "3.10"
  Using cached importlib_metadata-4.8.2-py3-none-any.whl (17 kB)
Collecting attrs<22,>=19
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.0-py3-none-any.whl (11 kB)
Collecting linkify-it-py~=1.0; extra == "linkify"
  Using cached linkify_it_py-1.0.2-py3-none-any.whl (19 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10"
  Using cached ruamel.yaml.clib-0.2.6-cp38-cp38-manylinux1_x86_64.whl (570 kB)
Collecting zipp>=0.5
  Using cached zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting uc-micro-py
  Using cached uc_micro_py-1.0.1-py3-none-any.whl (6.2 kB)
Installing collected packages: attrs, mdurl, uc-micro-py, linkify-it-py, markdown-it-py, mdit-py-plugins, tomli, zipp, importlib-metadata, mdformat, mdformat-tables, mdformat-gfm, ruamel.yaml.clib, ruamel.yaml, mdformat-frontmatter, toml, mdformat-config
Successfully installed attrs-21.2.0 importlib-metadata-4.8.2 linkify-it-py-1.0.2 markdown-it-py-2.0.0 mdformat-0.7.11 mdformat-config-0.1.3 mdformat-frontmatter-0.4.1 mdformat-gfm-0.3.5 mdformat-tables-0.4.1 mdit-py-plugins-0.3.0 mdurl-0.1.0 ruamel.yaml-0.17.17 ruamel.yaml.clib-0.2.6 toml-0.10.2 tomli-1.2.2 uc-micro-py-1.0.1 zipp-3.6.0
(testvenv) foo@bar:~$ mdformat test.md 
(testvenv) foo@bar:~$ mdformat --version
mdformat 0.7.11 (mdformat_tables: 0.4.1, mdformat_gfm: 0.3.5, mdformat_frontmatter: 0.4.1, mdformat_config: 0.1.3)
(testvenv) foo@bar:~$
~~~~

**Comment by hukkin** [comment] 2021-12-08 22:17
ah sorry wait i didn't have JSON in the info string :man_facepalming:

**Comment by hukkin** [comment] 2021-12-08 22:21
Still not able to reproduce with `json` in the info string:

~~~~console
foo@bar:~$ python3 -m venv testvenv
foo@bar:~$ source testvenv/bin/activate
(testvenv) foo@bar:~$ printf '```json\n{\n  \"double_quotes\": \"Escaped\\\"Double quotes\\\".\"\n}\n```\n' > test.md
(testvenv) foo@bar:~$ cat test.md 
```json
{
  "double_quotes": "Escaped\"Double quotes\"."
}
```
(testvenv) foo@bar:~$ pip install mdformat-gfm mdformat-frontmatter mdformat-config
Collecting mdformat-gfm
  Using cached mdformat_gfm-0.3.5-py3-none-any.whl (4.9 kB)
Collecting mdformat-frontmatter
  Using cached mdformat_frontmatter-0.4.1-py3-none-any.whl (4.5 kB)
Collecting mdformat-config
  Using cached mdformat_config-0.1.3-py3-none-any.whl (3.1 kB)
Collecting mdit-py-plugins<0.4.0,>=0.2.0
  Using cached mdit_py_plugins-0.3.0-py3-none-any.whl (43 kB)
Collecting mdformat-tables>=0.4.0
  Using cached mdformat_tables-0.4.1-py3-none-any.whl (4.6 kB)
Collecting mdformat<0.8.0,>=0.7.5
  Using cached mdformat-0.7.11-py3-none-any.whl (27 kB)
Collecting markdown-it-py[linkify]
  Using cached markdown_it_py-2.0.0-py3-none-any.whl (83 kB)
Collecting ruamel.yaml
  Using cached ruamel.yaml-0.17.17-py3-none-any.whl (109 kB)
Collecting toml>=0.10.0
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting tomli>=1.1.0
  Using cached tomli-1.2.2-py3-none-any.whl (12 kB)
Collecting importlib-metadata>=3.6.0; python_version < "3.10"
  Using cached importlib_metadata-4.8.2-py3-none-any.whl (17 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.0-py3-none-any.whl (11 kB)
Collecting attrs<22,>=19
  Using cached attrs-21.2.0-py2.py3-none-any.whl (53 kB)
Collecting linkify-it-py~=1.0; extra == "linkify"
  Using cached linkify_it_py-1.0.2-py3-none-any.whl (19 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.10"
  Using cached ruamel.yaml.clib-0.2.6-cp38-cp38-manylinux1_x86_64.whl (570 kB)
Collecting zipp>=0.5
  Using cached zipp-3.6.0-py3-none-any.whl (5.3 kB)
Collecting uc-micro-py
  Using cached uc_micro_py-1.0.1-py3-none-any.whl (6.2 kB)
Installing collected packages: mdurl, attrs, uc-micro-py, linkify-it-py, markdown-it-py, mdit-py-plugins, tomli, zipp, importlib-metadata, mdformat, mdformat-tables, mdformat-gfm, ruamel.yaml.clib, ruamel.yaml, mdformat-frontmatter, toml, mdformat-config
Successfully installed attrs-21.2.0 importlib-metadata-4.8.2 linkify-it-py-1.0.2 markdown-it-py-2.0.0 mdformat-0.7.11 mdformat-config-0.1.3 mdformat-frontmatter-0.4.1 mdformat-gfm-0.3.5 mdformat-tables-0.4.1 mdit-py-plugins-0.3.0 mdurl-0.1.0 ruamel.yaml-0.17.17 ruamel.yaml.clib-0.2.6 toml-0.10.2 tomli-1.2.2 uc-micro-py-1.0.1 zipp-3.6.0
(testvenv) foo@bar:~$ mdformat test.md 
(testvenv) foo@bar:~$ mdformat --version
mdformat 0.7.11 (mdformat_tables: 0.4.1, mdformat_gfm: 0.3.5, mdformat_frontmatter: 0.4.1, mdformat_config: 0.1.3)
(testvenv) foo@bar:~$
~~~~

**Comment by hukkin** [comment] 2021-12-08 22:22
@butler54 Would you be able provide reproduction steps similar to my command line output?

**Comment by hukkin** [comment] 2022-01-14 00:56
@butler54 Friendly reminder: I will need input that I can reproduce the error with. Else I will close the issue in say a month or two.

**Closed** 2022-02-14 11:14 UTC
Labels: bug, plugin, needs reproduction
