### ISSUE TITLE
`--wrap n` should respect tables

### ISSUE THREAD

**Issue by gwpl** [executablebooks/mdformat#397] opened 2023-04-27 16:56 UTC
### Describe the bug

Seems like `--wrap` is breaking table structure.

Suggestion: `--wrap` should ignore wrapping tables.

### Reproduce the bug

```
$ cat t.md 
# Table Test

| xxxxx | xxxxxxxxxxx x | xxxxxxxxxxx x | xxxxxxxxxxx x | xxxxxxxxxxxx | xxxxxxxx xxxxxxx |
| --- | --- | --- | --- | --- | --- |
| xxxxxxx xxxxxxxx xxxxxxxxxxxx | xx x | xx x | xx x | xx x | xx xxx |
| x xxxxxxxxx xx xxx | x x | xx x | xx x | xx x | xx xxx |
| x xxxxxxxxx xx xxx | x x | xx x | xx x | xx x | xx xxx |
| xxxxxxxx xxxxx xx xxx xxx | - | - | - | - | xxx xxx |
| x xxx x xxx xxx xxxxxxxx | - | - | x xxx/x | x xxx/x | - |

$ cat t.md | mdformat -  # without --wrap 60 seems fine
# Table Test

| xxxxx | xxxxxxxxxxx x | xxxxxxxxxxx x | xxxxxxxxxxx x | xxxxxxxxxxxx | xxxxxxxx xxxxxxx |
| --- | --- | --- | --- | --- | --- |
| xxxxxxx xxxxxxxx xxxxxxxxxxxx | xx x | xx x | xx x | xx x | xx xxx |
| x xxxxxxxxx xx xxx | x x | xx x | xx x | xx x | xx xxx |
| x xxxxxxxxx xx xxx | x x | xx x | xx x | xx x | xx xxx |
| xxxxxxxx xxxxx xx xxx xxx | - | - | - | - | xxx xxx |
| x xxx x xxx xxx xxxxxxxx | - | - | x xxx/x | x xxx/x | - |
$ cat t.md | mdformat --wrap 60 -  # with --wrap seems wrong
# Table Test

| xxxxx | xxxxxxxxxxx x | xxxxxxxxxxx x | xxxxxxxxxxx x |
xxxxxxxxxxxx | xxxxxxxx xxxxxxx | | --- | --- | --- | --- |
--- | --- | | xxxxxxx xxxxxxxx xxxxxxxxxxxx | xx x | xx x |
xx x | xx x | xx xxx | | x xxxxxxxxx xx xxx | x x | xx x |
xx x | xx x | xx xxx | | x xxxxxxxxx xx xxx | x x | xx x |
xx x | xx x | xx xxx | | xxxxxxxx xxxxx xx xxx xxx | - | - |
\- | - | xxx xxx | | x xxx x xxx xxx xxxxxxxx | - | - | x
xxx/x | x xxx/x | - |

```

### List your environment

$ python --version
Python 3.10.10

**Comment by hukkin** [comment] 2023-04-27 17:32
Closing as duplicate of https://github.com/executablebooks/mdformat/issues/393

**Closed by hukkin** 2023-04-27 17:32 UTC
Labels: bug

**Comment by gwpl** [comment] 2023-04-27 21:11
https://github.com/orgs/executablebooks/discussions/1008
