### ISSUE TITLE
Word-wrap on sentence (punctuation) and width.

### ISSUE THREAD

**Issue by mdeweerd** [executablebooks/mdformat#422] opened 2024-01-28 15:40 UTC
### Context

[Start each sentence on a new line. Make lines short.](https://mdformat.readthedocs.io/en/stable/users/style.html#:~:text=Start%20each%20sentence%20on%20a%20new%20line.%20Make%20lines%20short%2C) as indicated in the documentation.

Currently we can make lines short with a target wrap width.  However that breaks line wrapping at punctuations unless we add a double space or backslash.

### Proposal

It's be nice if - while word-wrapping for line-length - mdformat could:
- respect line wrapping already in place at a punctuation ('.', ';');
- line-wrap at punctuations ('.', ';').

The options could take an optional parameter with the list of punctuations to apply them to.

### Tasks and updates

- [ ] Agree on options;
- [ ] Implement the respect of existing line-wrapping on punctuation.
- [ ] IMplement adding line-wrapping on punctuation.

**Comment by hukkin** [comment] 2024-01-30 12:50
Closing as dupe of https://github.com/executablebooks/mdformat/issues/4

**Closed by hukkin** 2024-01-30 12:50 UTC
Labels: enhancement
