### ISSUE TITLE
Not Working In Python 3.11?

### ISSUE THREAD

**Issue by whinee** [executablebooks/mdformat#408] opened 2023-08-23 07:37 UTC
### Describe the bug

**context**
I have been using this program for a long time now. It had worked in python 3.10, but when I upgraded to python 3.11, it doesnt work anymore.

**expectation**
I expected for the program to format markdown files under `docs` directory.

**bug**
But instead, it throws the following exception:

```text
Traceback (most recent call last):
  File "/home/whine/whi_ne/3/projects/personal/tools/snippets.py/pyenv/bin/mdformat", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/whine/whi_ne/3/projects/personal/tools/snippets.py/pyenv/lib/python3.11/site-packages/mdformat/__main__.py", line 8, in run
    exit_code = mdformat._cli.run(sys.argv[1:])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whine/whi_ne/3/projects/personal/tools/snippets.py/pyenv/lib/python3.11/site-packages/mdformat/_cli.py", line 42, in run
    arg_parser = make_arg_parser(enabled_parserplugins, enabled_codeformatters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whine/whi_ne/3/projects/personal/tools/snippets.py/pyenv/lib/python3.11/site-packages/mdformat/_cli.py", line 138, in make_arg_parser
    plugin_versions_str = get_plugin_versions_str(parser_extensions, codeformatters)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whine/whi_ne/3/projects/personal/tools/snippets.py/pyenv/lib/python3.11/site-packages/mdformat/_cli.py", line 294, in get_plugin_versions_str
    plugin_versions = get_plugin_versions(parser_extensions, codeformatters)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whine/whi_ne/3/projects/personal/tools/snippets.py/pyenv/lib/python3.11/site-packages/mdformat/_cli.py", line 282, in get_plugin_versions
    package_version = importlib_metadata.version(package_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 1008, in version
    return distribution(distribution_name).version
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 561, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.
```

**problem**
This is a problem for people using this program, as they cannot run the program.

### Reproduce the bug

1. Have a directory named `docs` containing markdown files.
1. Run the following command:
```
python -m venv pyenv/
source pyenv/bin/activate
python -m pip install --upgrade pip
python -m pip install mdformat mdformat-gfm mdformat-frontmatter mdformat-footnote
mdformat docs
```

### List your environment

Python: 3.11.3
OS: Arch Linux x86_64
Kernel: 6.4.11-arch2-1

**Comment by hukkin** [comment] 2023-09-27 12:19
Thanks for the issue!

Unfortunately I am not able to reproduce your issue. Also, all tests pass in GitHub actions for both Python 3.11 and 3.12-dev. What version of mdformat are you running (`mdformat --version`)? Could you try using the latest?

**Comment by duongdominhchau** [comment] 2023-10-05 06:35
I also use ArchLinux but doesn't have this problem. Could you please update your system and retry? Below is what I used while following your reproduce instruction, but it works correctly without any error.

```console
$ python --version
Python 3.11.5
$ which python
/home/chau/pyenv/bin/python
$ ls -l $(which python)
lrwxrwxrwx 14k chau chau  5 Oct 13:31 /home/chau/pyenv/bin/python -> /usr/sbin/python
$ mdformat --version
mdformat 0.7.17 (mdformat_gfm: 0.3.5, mdformat_frontmatter: 2.0.1, mdformat_footnote: 0.1.1, mdformat_tables: 0.4.1)
```

**Comment by sanmai-NL** [comment] 2023-10-24 12:07
It works for me as well, MacOS and Python 3.11.

**Comment by hukkin** [comment] 2024-01-02 14:25
I'm closing now as I and others are unable to reproduce. If the issue still remains, please reopen, and attach the output of `mdformat --version`.

**Closed by hukkin** 2024-01-02 14:25 UTC
Labels: bug
